openapi: 3.0.3
info:
  title: MIDI2InstrumentLab API
  version: 1.0.0
  description: >-
    Slim A/V Workbench service API for sessions, headless runs, artifacts, AU introspection,
    and mapping helpers. Session schema v0 is intentionally minimal and will evolve.
servers:
  - url: /
tags:
  - name: health
  - name: sessions
  - name: runs
  - name: artifacts
  - name: introspection
  - name: mapping
paths:
  /health:
    get:
      tags: [health]
      summary: Liveness probe
      operationId: health
      x-fountain.allow-as-tool: true
      responses:
        '200':
          description: ok
          content:
            text/plain:
              schema: { type: string, example: ok }
  /sessions:
    post:
      tags: [sessions]
      summary: Create a session
      operationId: sessionsCreate
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Session' }
            examples:
              minimal:
                value:
                  schema: avw.session.v0
                  transport: { bpm: 120, meter: '4/4', loop: true, loopStart: 0, loopEnd: 4 }
                  tracks: [ { id: t1, instrument: { kind: midi2-internal }, clips: [] } ]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/SessionRef' }
        '400': { $ref: '#/components/responses/Problem400' }
  /sessions/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema: { type: string }
    get:
      tags: [sessions]
      summary: Get a session
      operationId: sessionsGet
      responses:
        '200':
          description: Session
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Session' }
        '404': { $ref: '#/components/responses/Problem404' }
    put:
      tags: [sessions]
      summary: Replace a session
      operationId: sessionsPut
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Session' }
      responses:
        '204': { description: Updated }
        '400': { $ref: '#/components/responses/Problem400' }
        '404': { $ref: '#/components/responses/Problem404' }
    delete:
      tags: [sessions]
      summary: Delete a session
      operationId: sessionsDelete
      responses:
        '204': { description: Deleted }
        '404': { $ref: '#/components/responses/Problem404' }
  /runs:
    post:
      tags: [runs]
      summary: Start a headless run
      operationId: runsStart
      x-fountain.allow-as-tool: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId: { type: string, description: 'Use an existing session id' }
                session: { $ref: '#/components/schemas/Session' }
                ttlSecs: { type: integer, minimum: 0 }
              oneOf:
                - required: [sessionId]
                - required: [session]
            examples:
              byId:
                value: { sessionId: 'abc123' }
              inline:
                value:
                  session:
                    schema: avw.session.v0
                    transport: { bpm: 120, meter: '4/4' }
                    tracks: [ { id: t1, instrument: { kind: midi2-internal }, clips: [] } ]
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Run' }
        '400': { $ref: '#/components/responses/Problem400' }
  /runs/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema: { type: string }
    get:
      tags: [runs]
      summary: Get run status
      operationId: runsGet
      x-fountain.allow-as-tool: true
      responses:
        '200':
          description: Run
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Run' }
        '404': { $ref: '#/components/responses/Problem404' }
  /runs/{id}/artifacts:
    parameters:
      - in: path
        name: id
        required: true
        schema: { type: string }
    get:
      tags: [artifacts]
      summary: List artifacts for a run
      operationId: artifactsList
      x-fountain.allow-as-tool: true
      responses:
        '200':
          description: Artifacts
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items: { $ref: '#/components/schemas/Artifact' }
        '404': { $ref: '#/components/responses/Problem404' }
  /runs/{id}/artifacts/{name}:
    parameters:
      - in: path
        name: id
        required: true
        schema: { type: string }
      - in: path
        name: name
        required: true
        schema: { type: string }
    get:
      tags: [artifacts]
      summary: Fetch artifact content
      operationId: artifactsGet
      x-fountain.allow-as-tool: true
      responses:
        '200':
          description: Artifact content (text or binary)
          content:
            application/octet-stream:
              schema: { type: string, format: binary }
            text/plain:
              schema: { type: string }
        '404': { $ref: '#/components/responses/Problem404' }
  /introspect/au:
    post:
      tags: [introspection]
      summary: Introspect an AU and list parameters
      operationId: introspectAU
      x-fountain.allow-as-tool: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [identifier]
              properties:
                identifier: { type: string, description: 'Bundle identifier or component string' }
                scope: { type: string, description: 'instrument|effect', enum: [instrument, effect] }
            examples:
              byId: { value: { identifier: 'com.vendor.plugin.Instrument', scope: instrument } }
      responses:
        '200':
          description: Parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items: { $ref: '#/components/schemas/AUParameter' }
        '400': { $ref: '#/components/responses/Problem400' }
  /mapping/generate:
    post:
      tags: [mapping]
      summary: Propose OpenAPI + Facts from AU parameters or a mapping sketch
      operationId: mappingGenerate
      x-fountain.allow-as-tool: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agentId: { type: string, description: 'fountain.coach/agent/<name>/service' }
                parameters:
                  type: array
                  items: { $ref: '#/components/schemas/AUParameter' }
                strategy: { type: string, description: 'Mapping hint (e.g., direct, normalized)' }
            examples:
              simple:
                value:
                  agentId: fountain.coach/agent/mpe-synth/service
                  parameters: [ { id: 1, name: Gain, min: 0, max: 1 } ]
                  strategy: direct
      responses:
        '200':
          description: Proposed mapping
          content:
            application/json:
              schema:
                type: object
                properties:
                  openapi: { type: object, description: 'OpenAPI document (object form)' }
                  facts: { type: object, description: 'Generated PE facts' }
        '400': { $ref: '#/components/responses/Problem400' }

components:
  schemas:
    Problem:
      type: object
      description: RFC 7807 Problem Details
      properties:
        type: { type: string }
        title: { type: string }
        status: { type: integer }
        detail: { type: string }
        instance: { type: string }
      required: [title, status]
    SessionRef:
      type: object
      properties:
        id: { type: string }
      required: [id]
    Session:
      type: object
      description: Minimal session schema (v0). Evolves over time; clients should tolerate extra fields.
      properties:
        schema: { type: string, example: avw.session.v0 }
        meta:
          type: object
          additionalProperties: true
        transport:
          type: object
          properties:
            bpm: { type: number, example: 120 }
            meter: { type: string, example: '4/4' }
            loop: { type: boolean, default: true }
            loopStart: { type: number, example: 0.0 }
            loopEnd: { type: number, example: 4.0 }
          required: [bpm, meter]
        tracks:
          type: array
          items:
            type: object
            properties:
              id: { type: string }
              name: { type: string }
              instrument: { type: object, additionalProperties: true }
              clips:
                type: array
                items:
                  type: object
                  properties:
                    id: { type: string }
                    start: { type: number }
                    length: { type: number }
                    notes:
                      type: array
                      items:
                        type: object
                        properties:
                          time: { type: number }
                          pitch: { type: integer }
                          velocity: { type: integer }
                          length: { type: number }
                        required: [time, pitch]
                  required: [id, start, length]
            required: [id, instrument]
      required: [schema, transport, tracks]
      additionalProperties: true
    Run:
      type: object
      properties:
        id: { type: string }
        status: { type: string, enum: [queued, running, succeeded, failed] }
        createdAt: { type: string, format: date-time }
        finishedAt: { type: string, format: date-time, nullable: true }
        artifacts:
          type: array
          items: { $ref: '#/components/schemas/Artifact' }
      required: [id, status, createdAt]
    Artifact:
      type: object
      properties:
        name: { type: string }
        contentType: { type: string }
        size: { type: integer, format: int64 }
        href: { type: string }
      required: [name]
    AUParameter:
      type: object
      properties:
        id: { type: integer, description: 'AU param identifier' }
        name: { type: string }
        min: { type: number }
        max: { type: number }
        unit: { type: string, nullable: true }
        default: { type: number, nullable: true }
      required: [id, name, min, max]
  responses:
    Problem400:
      description: Bad Request
      content:
        application/problem+json:
          schema: { $ref: '#/components/schemas/Problem' }
    Problem404:
      description: Not Found
      content:
        application/problem+json:
          schema: { $ref: '#/components/schemas/Problem' }
